#!/bin/bash
# Script to remove color attributes from .dot files generated by opt -passes=dot-cfg
# Usage: scripts/filter-color.sh <input.dot> [--inplace | --output <output.dot>]
# It will remove the "color=..." attribute from the .dot file, which is used to color the nodes in the CFG. This is useful to make the CFG more readable, especially when
# and also remove the "style=filled" attribute, which is used to fill the nodes with color. This is useful to make the CFG more readable, especially when there are many nodes and edges.
FILENAME="$1"
if [ -z "$FILENAME" ]; then
  echo "Usage: $0 <input.dot> [--inplace | --output <output.dot>]"
  exit 1
fi
if [ ! -f "$FILENAME" ]; then
  echo "Error: file not found: $FILENAME"
  exit 1
fi

INPLACE=1
OUTPUT_FILE="$FILENAME"

shift
while [ $# -gt 0 ]; do
  case "$1" in
    --inplace)
      INPLACE=1
      OUTPUT_FILE="$FILENAME"
      shift
      ;;
    --output)
      if [ -z "$2" ]; then
        echo "Error: --output requires a file path"
        exit 1
      fi
      INPLACE=0
      OUTPUT_FILE="$2"
      shift 2
      ;;
    -h|--help)
      echo "Usage: $0 <input.dot> [--inplace | --output <output.dot>]"
      exit 0
      ;;
    *)
      echo "Error: unknown option: $1"
      echo "Usage: $0 <input.dot> [--inplace | --output <output.dot>]"
      exit 1
      ;;
  esac
done

echo "Filtering color attributes from $FILENAME..."
TMP_FILE="${OUTPUT_FILE}.tmp.$$"

# Use a temp file instead of sed -i to stay compatible with macOS BSD sed and GNU sed.
sed -E 's/(^|[[:space:],])color="[^"]*",?/\1/g' "$FILENAME" > "$TMP_FILE"
sed -E 's/[[:space:]]*style=filled,?//g' "$TMP_FILE" > "${TMP_FILE}.2"
sed -E 's/[[:space:]]*fill,?//g' "${TMP_FILE}.2" > "${TMP_FILE}.3"
mv "${TMP_FILE}.3" "$OUTPUT_FILE"
rm -f "$TMP_FILE" "${TMP_FILE}.2"

if [ "$INPLACE" -eq 1 ]; then
  echo "Filtered .dot file saved to $OUTPUT_FILE"
else
  echo "Filtered .dot file written to $OUTPUT_FILE"
fi

# Convert to png again to see the changes (optional, you can skip this step if you want to keep the original .dot file)
PNG_FILE="${OUTPUT_FILE%.dot}.png"
dot -Tpng "$OUTPUT_FILE" -o "$PNG_FILE"
echo "Filtered .dot file saved to $OUTPUT_FILE and updated PNG saved to $PNG_FILE"
